services:
  nats:
    image: nats:2-alpine
    container_name: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: nats-server -m 8222 -D

  rethinkdb:
    image: rethinkdb:2.4.4-bookworm-slim
    container_name: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
    command: rethinkdb -d /data/rdb --bind 0.0.0.0 --server-tag default --http-port 8080 --driver-port 28015
    volumes:
      - ${PWD}/database:/data/rdb:rw

  worker:
    image: kronk:latest
    container_name: worker
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    command: poetry run python -m kronk.worker
    environment:
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - NATS_HOST=nats
      - NATS_PORT=4222

  distributor:
    image: kronk:latest
    container_name: distributor
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    command: poetry run python -m kronk.distributor
    environment:
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - NATS_HOST=nats
      - NATS_PORT=4222
