version: '3.7'
services:
  nats:
    image: nats:2-alpine
    container_name: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: nats-server -m 8222 -D

  rethinkdb:
    image: rethinkdb:2.4.0
    container_name: rethinkdb
    ports:
      - "8080:8080"
      - "28015:28015"
    command: rethinkdb -d /data/rdb --bind 0.0.0.0 --server-tag default --http-port 8080 --driver-port 28015
    volumes:
      - type: bind
        source: /srv # Swap this for something more appropriate
        target: /data/rdb

  worker:
    image: kronk:latest
    container_name: worker
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    command: pipenv run worker
    environment:
      - RDB_ENDPOINT=rethinkdb
      - NATS_ENDPOINT=nats://nats:4222

  distributor:
    image: kronk:latest
    container_name: distributor
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    command: pipenv run distributor
    environment:
      - RDB_ENDPOINT=rethinkdb
      - NATS_ENDPOINT=nats://nats:4222

volumes:
  rdbdata:
